name: "Compile Project on Linux and MacOS"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux-macos:
    strategy:
      fail-fast: false
      matrix:
        os-version: [ ubuntu-latest, macos-latest ]
        compiler: [ latest, gcc-latest, clang, clang-11, clang++-12, clang++-14, clang++-15 ]
        exclude:
          - os-version: macos-latest
            compiler: latest
          - os-version: macos-latest
            compiler: gcc-latest
          - os-version: macos-latest
            compiler: gcc

    runs-on: ${{ matrix.os-version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: ${{ matrix.compiler }}
      - name: Check Compiler
        shell: bash
        env:
            CC: ${{ steps.install_cc.outputs.cc }}
            CXX: ${{ steps.install_cc.outputs.cxx }}
        run: |
          $CC --version
          $CXX --version
      - name: Build
        run: make
